# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Socialtext-Resting-Utils
version:      0.16
version_from: lib/Socialtext/Resting/Utils.pm
installdirs:  site
requires:
    Getopt::Long:                  2.36
    JSON:                          0
    Socialtext::Resting:           0.21
    Test::Mock::LWP:               0
    Test::More:                    0
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
