--- #YAML:1.0
name:               Socialtext-Resting-Utils
version:            0.21
abstract:           Utilities for Socialtext REST APIs
author:
    - Luke Closs <cpan@5thplane.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Crypt::CBC:           0
    Crypt::DES:           0
    Getopt::Long:         2.36
    JSON::XS:             2.01
    Socialtext::Resting:  0.27
    Test::Mock::LWP:      0
    Test::More:           0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
